github:
  description: "CloudStack Terraform Provider"
  homepage: https://cloudstack.apache.org
  labels:
    - terraform
    - cloudstack
    - go
  features:
    wiki: true
    issues: true
    projects: true

  protected_branches:
    main:
      required_status_checks:
        contexts:
           - build
           - all-jobs-passed

  collaborators:
    - kiranchavala
    - vishesh92
    - fabiomatavelli
    - CodeBleu
