name: Build-Check

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16.x
        
    - name: Set up tools     
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        chmod 777 $GOPATH/bin
        mkdir -p $GOPATH/src/github.com/apache;
        cd $GOPATH/src/github.com/apache
        git clone git@github.com:apache/cloudstack-terraform-provider
        cd $GOPATH/src/github.com/apache/cloudstack-terraform-provider
        
    - name: Build
      run: |        
        make build
        
    - name: Test
      run: make test
